name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: i686-pc-windows-msvc
          rustflags: ""
      - name: Build x64
        run: cargo build --verbose --release --target x86_64-pc-windows-msvc
      - name: Build x86
        run: cargo build --verbose --release --target i686-pc-windows-msvc
      - uses: actions/upload-artifact@v4
        with:
          path: target/*/release/*.exe

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - uses: actions-rust-lang/rustfmt@v1
